{"variants":[{"paths":["\/documentation\/pingonesdk\/pingonegeo\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@PingOneSDK@E@PingOneGeo","modules":[{"name":"PingOneSDK","relatedModules":["Swift"]}],"title":"!=(_:_:)","role":"symbol","roleHeading":"Operator","symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"extendedModule":"Swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/!=(_:_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Equatable-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}],"title":"PingOneGeo","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/!=(_:_:)":{"url":"\/documentation\/pingonesdk\/pingonegeo\/!=(_:_:)","title":"!=(_:_:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/!=(_:_:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Equatable-Implementations":{"url":"\/documentation\/pingonesdk\/pingonegeo\/equatable-implementations","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PingOneGeo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title"},{"value":[{"text":"PingOneGeo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments"},{"value":[{"text":"PingOneGeo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle"}]}]}