{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Canada","interfaceLanguage":"swift"},"abstract":[{"text":"Canada","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingonegeo\/canada"]},{"paths":["\/documentation\/pingonesdk\/pingonegeo\/canada"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Canada"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeoCanada"}],"modules":[{"name":"PingOneSDK"}],"title":"PingOneGeo.Canada","roleHeading":"Case","role":"symbol","externalID":"c:@M@PingOneSDK@E@PingOneGeo@PingOneGeoCanada","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Canada","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Canada":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Canada","abstract":[{"text":"Canada","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Canada","kind":"identifier"}],"title":"PingOneGeo.Canada","url":"\/documentation\/pingonesdk\/pingonegeo\/canada","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOneGeoCanada"}],"type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}],"title":"PingOneGeo","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PingOneGeoCanada","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"PingOneGeoCanada","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"PingOneGeoCanada"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Canada\/title","value":"PingOneGeoCanada"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Canada\/fragments","value":[{"kind":"identifier","text":"PingOneGeoCanada"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title","value":"PingOneGeo"},{"value":[{"text":"PingOneGeo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle","value":[{"text":"PingOneGeo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}