{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","modules":[{"name":"PingOneSDK"}],"role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"]]},"kind":"article","sections":[],"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/!=(_:_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingonegeo\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}],"title":"PingOneGeo","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/!=(_:_:)":{"url":"\/documentation\/pingonesdk\/pingonegeo\/!=(_:_:)","title":"!=(_:_:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/!=(_:_:)","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PingOneGeo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments","value":[{"text":"PingOneGeo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle","value":[{"text":"PingOneGeo","kind":"identifier"}],"op":"replace"}]}]}