{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PingOneGeoEurope"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"Europe","kind":"identifier"}],"title":"PingOneGeo.Europe","modules":[{"name":"PingOneSDK"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@PingOneGeo@PingOneGeoEurope","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Europe"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Europe","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/pingonegeo\/europe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingonegeo\/europe"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Europe"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Europe":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Europe","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PingOneGeoEurope","kind":"identifier"}],"abstract":[{"type":"text","text":"Europe"}],"role":"symbol","title":"PingOneGeo.Europe","url":"\/documentation\/pingonesdk\/pingonegeo\/europe","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Europe","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}],"title":"PingOneGeo","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"PingOneGeoEurope","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PingOneGeoEurope","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PingOneGeoEurope","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Europe\/title","value":"PingOneGeoEurope"},{"op":"replace","value":[{"text":"PingOneGeoEurope","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Europe\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title","value":"PingOneGeo","op":"replace"},{"op":"replace","value":[{"text":"PingOneGeo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle","value":[{"kind":"identifier","text":"PingOneGeo"}]}]}]}