{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthAmerica"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/pingonegeo\/northamerica"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/pingonegeo\/northamerica"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/NorthAmerica","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"North America"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthAmerica"}],"title":"PingOneGeo.NorthAmerica","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PingOneSDK@E@PingOneGeo@PingOneGeoNorthAmerica","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/NorthAmerica":{"role":"symbol","title":"PingOneGeo.NorthAmerica","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"NorthAmerica"}],"abstract":[{"type":"text","text":"North America"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/NorthAmerica","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}],"url":"\/documentation\/pingonesdk\/pingonegeo\/northamerica"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"role":"symbol","title":"PingOneGeo","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOneGeo"}],"abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}],"url":"\/documentation\/pingonesdk\/pingonegeo"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PingOneGeoNorthAmerica"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1NorthAmerica\/title","value":"PingOneGeoNorthAmerica"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1NorthAmerica\/fragments","value":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title","value":"PingOneGeo"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments","value":[{"kind":"identifier","text":"PingOneGeo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}