{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Singapore"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Singapore"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Singapore","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingonegeo\/singapore"]},{"paths":["\/documentation\/pingonesdk\/pingonegeo\/singapore"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"Singapore","kind":"identifier"}],"title":"PingOneGeo.Singapore","navigatorTitle":[{"kind":"identifier","text":"PingOneGeoSingapore"}],"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@PingOneGeo@PingOneGeoSingapore","role":"symbol"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Singapore":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/singapore","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Singapore","abstract":[{"text":"Singapore","type":"text"}],"title":"PingOneGeo.Singapore","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Singapore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeoSingapore"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}],"title":"PingOneGeo","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"PingOneGeoSingapore"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"PingOneGeoSingapore"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"PingOneGeoSingapore","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PingOneGeoSingapore","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Singapore\/title","op":"replace"},{"value":[{"text":"PingOneGeoSingapore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Singapore\/fragments"},{"op":"replace","value":"PingOneGeo","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments","value":[{"text":"PingOneGeo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PingOneGeo"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}