{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-swift.property"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","title":"testResult","navigatorTitle":[{"kind":"identifier","text":"testResult"}],"externalID":"c:@M@PingOneSDK@objc(cs)NotificationTest(py)testResult","symbolKind":"property","modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"testResult","kind":"identifier"},{"kind":"text","text":": "},{"text":"NotificationTest","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","kind":"typeIdentifier","text":"TestResult"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-swift.property","interfaceLanguage":"swift"},"abstract":[{"text":"The test result represented by ","type":"text"},{"code":"TestResult","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"testResult"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","text":"NotificationTest"},{"text":".","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum","type":"topic","navigatorTitle":[{"text":"TestResult","kind":"identifier"}],"title":"NotificationTest.TestResult","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestResult"}],"kind":"symbol","abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"url":"\/documentation\/pingonesdk\/notificationtest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/TestResult":{"fragments":[{"kind":"identifier","text":"TestResult"}],"type":"topic","title":"TestResult","abstract":[{"text":"Public enum that describes the notification test result.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/testresult","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/testResult-swift.property":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"testResult"},{"kind":"text","text":": "},{"text":"NotificationTest","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"The test result represented by "},{"code":"TestResult","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-swift.property","kind":"symbol","title":"testResult","role":"symbol","navigatorTitle":[{"text":"testResult","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.property"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"testResult","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"testResult","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/TestResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@E@TestResult","text":"TestResult"},{"kind":"text","text":" "},{"text":"testResult","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","value":"NotificationTest"},{"value":[{"kind":"identifier","text":"NotificationTest"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments"},{"value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle"},{"value":"testResult","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-swift.property\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-swift.property\/fragments","op":"replace","value":[{"text":"testResult","kind":"identifier"}]}]}]}