{"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType\/init(rawValue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/authenticatormodel\/authenticatortype\/init(rawvalue:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","modules":[{"name":"PingOneSDK"}],"roleHeading":"Initializer","externalID":"s:10PingOneSDK18AuthenticatorModelC0D4TypeO8rawValueAESgSi_tcfc","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorType":{"url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatortype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticatorType","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticatorType","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AuthenticatorModel.AuthenticatorType","type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorType/init(rawValue:)":{"url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatortype\/init(rawvalue:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"init(rawValue:)","type":"topic"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"title":"AuthenticatorModel","type":"topic","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticatorModel"}],"url":"\/documentation\/pingonesdk\/authenticatormodel","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","value":[{"text":"AuthenticatorModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticatorModel"}],"op":"replace"}]}]}