{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationtest"]},{"paths":["\/documentation\/pingonesdk\/notificationtest"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationTest"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NotificationTest","kind":"identifier"}],"title":"NotificationTest","externalID":"c:@M@PingOneSDK@objc(cs)NotificationTest","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/name","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/resultsInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testDescription","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-swift.property"]},{"title":"Enumerations","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType"],"generated":true,"anchor":"Enumerations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/testResult-swift.property":{"role":"symbol","url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"testResult"},{"text":": ","kind":"text"},{"text":"NotificationTest","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","text":"TestResult"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-swift.property","navigatorTitle":[{"text":"testResult","kind":"identifier"}],"abstract":[{"text":"The test result represented by ","type":"text"},{"type":"codeVoice","code":"TestResult"},{"text":".","type":"text"}],"title":"testResult"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/resultsInfo":{"title":"resultsInfo","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"resultsInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"resultsInfo","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"In case the test didn’t pass, information that explains the failure reason and how to overcome it."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/resultsInfo","url":"\/documentation\/pingonesdk\/notificationtest\/resultsinfo"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/init":{"url":"\/documentation\/pingonesdk\/notificationtest\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType":{"type":"topic","title":"NotificationTest.TestType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestType"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testtype","navigatorTitle":[{"text":"TestType","kind":"identifier"}],"abstract":[{"text":"Public enum that describes the notification of all tests name, description, and resulstsInfo.","type":"text"}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/notificationtest","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}],"title":"NotificationTest","navigatorTitle":[{"kind":"identifier","text":"NotificationTest"}],"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"title":"NotificationTest.TestResult","type":"topic","abstract":[{"text":"Public enum that describes the notification test result.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TestResult"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum","navigatorTitle":[{"text":"TestResult","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/testDescription":{"title":"testDescription","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"testDescription","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"testDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The description of the test."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testDescription","url":"\/documentation\/pingonesdk\/notificationtest\/testdescription"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/name":{"title":"name","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"The name of the test.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/name","url":"\/documentation\/pingonesdk\/notificationtest\/name"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"NotificationTest","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"NotificationTest","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"NotificationTest"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/name","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/resultsInfo","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testDescription","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/testResult-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationTest"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-swift.property\/title","value":"testResult"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testResult-swift.property\/fragments","value":[{"kind":"identifier","text":"testResult"}],"op":"replace"},{"value":"resultsInfo","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1resultsInfo\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1resultsInfo\/fragments","value":[{"kind":"identifier","text":"resultsInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","op":"replace","value":"NotificationTest"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments","value":[{"text":"NotificationTest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle","value":[{"kind":"identifier","text":"NotificationTest"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testDescription\/title","value":"testDescription","op":"replace"},{"value":[{"kind":"identifier","text":"testDescription"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1testDescription\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1name\/title","value":"name","op":"replace"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest~1name\/fragments"}]}]}