{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OneTimePasscodeInfo","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"OneTimePasscodeInfo"}],"modules":[{"name":"PingOneSDK"}],"title":"OneTimePasscodeInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OneTimePasscodeInfo","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/passcode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/timeWindowSize","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validFrom","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validUntil"],"title":"Instance Properties","anchor":"Instance-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo"]}],"abstract":[{"text":"Public class that contains data of the One Time Passcode","type":"text"}],"references":{"doc://com.pingIdentity.PingOneSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject"},"doc://com.pingIdentity.PingOneSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/timeWindowSize":{"title":"timeWindowSize","navigatorTitle":[{"kind":"identifier","text":"timeWindowSize"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeWindowSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/timeWindowSize","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/timewindowsize","abstract":[{"type":"text","text":"The total life span of the passcode since it was created until it expired. The time unit is seconds"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/validUntil":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"validUntil","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The time of expiration of the code."},{"text":" ","type":"text"},{"type":"text","text":"it is provided in double format which holds the future time in milliseconds divided by 1000 to represent seconds"}],"url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/validuntil","navigatorTitle":[{"text":"validUntil","kind":"identifier"}],"type":"topic","title":"validUntil","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validUntil"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/passcode":{"role":"symbol","title":"passcode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passcode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"passcode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/passcode","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/passcode","abstract":[{"type":"text","text":"The generated passcode"}]},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo":{"role":"symbol","navigatorTitle":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Public class that contains data of the One Time Passcode"}],"title":"OneTimePasscodeInfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OneTimePasscodeInfo","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/onetimepasscodeinfo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/validFrom":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validFrom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"text":"The time of creation of the passcode.","type":"text"}],"url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/validfrom","navigatorTitle":[{"text":"validFrom","kind":"identifier"}],"type":"topic","title":"validFrom","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validFrom"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"OneTimePasscodeInfo","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/passcode","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/timeWindowSize","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validFrom","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validUntil"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OneTimePasscodeInfo"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1timeWindowSize\/title","value":"timeWindowSize"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1timeWindowSize\/fragments","value":[{"text":"timeWindowSize","kind":"identifier"}]},{"value":"validUntil","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validUntil\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validUntil\/fragments","op":"replace","value":[{"kind":"identifier","text":"validUntil"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1passcode\/title","value":"passcode"},{"value":[{"kind":"identifier","text":"passcode"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1passcode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/title","op":"replace","value":"OneTimePasscodeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/fragments","value":[{"kind":"identifier","text":"OneTimePasscodeInfo"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/navigatorTitle","op":"replace","value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}]},{"op":"replace","value":"validFrom","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validFrom\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validFrom\/fragments","op":"replace","value":[{"kind":"identifier","text":"validFrom"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}