{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Australia","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Canada","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Europe","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/NorthAmerica","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Singapore"],"anchor":"Enumeration-Cases"},{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/init(rawValue:)"],"generated":true},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/stringName()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PingOneGeo","kind":"identifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/Se","doc:\/\/com.pingIdentity.PingOneSDK\/SE","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingonegeo"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingonegeo"]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"metadata":{"title":"PingOneGeo","roleHeading":"Enumeration","modules":[{"name":"PingOneSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"externalID":"c:@M@PingOneSDK@E@PingOneGeo","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/stringName()":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/stringname()","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/stringName()","abstract":[{"type":"text","text":"Fetch the PingOneGeo enum string name"}],"title":"stringName()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stringName"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.pingIdentity.PingOneSDK/SH":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Singapore":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/singapore","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Singapore","abstract":[{"text":"Singapore","type":"text"}],"title":"PingOneGeo.Singapore","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Singapore","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeoSingapore"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Europe":{"url":"\/documentation\/pingonesdk\/pingonegeo\/europe","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Europe","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOneGeoEurope"}],"title":"PingOneGeo.Europe","abstract":[{"type":"text","text":"Europe"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Europe"},"doc://com.pingIdentity.PingOneSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Equatable-Implementations":{"url":"\/documentation\/pingonesdk\/pingonegeo\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Equatable-Implementations"},"doc://com.pingIdentity.PingOneSDK/SE":{"title":"Swift.Encodable","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SE"},"doc://com.pingIdentity.PingOneSDK/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Canada":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/canada","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Canada","abstract":[{"type":"text","text":"Canada"}],"title":"PingOneGeo.Canada","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Canada"}],"navigatorTitle":[{"text":"PingOneGeoCanada","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/Se","title":"Swift.Decodable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}],"title":"PingOneGeo","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/RawRepresentable-Implementations":{"url":"\/documentation\/pingonesdk\/pingonegeo\/rawrepresentable-implementations","kind":"article","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/RawRepresentable-Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/init(rawValue:)":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/init(rawvalue:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/Australia":{"url":"\/documentation\/pingonesdk\/pingonegeo\/australia","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Australia","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOneGeoAustralia"}],"title":"PingOneGeo.Australia","abstract":[{"type":"text","text":"Australia"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Australia"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo/NorthAmerica":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo\/northamerica","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/NorthAmerica","abstract":[{"type":"text","text":"North America"}],"title":"PingOneGeo.NorthAmerica","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NorthAmerica"}],"navigatorTitle":[{"text":"PingOneGeoNorthAmerica","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"PingOneGeo","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneGeo"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneGeo"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Australia","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Canada","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Europe","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/NorthAmerica","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo\/Singapore"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PingOneGeo","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PingOneGeoSingapore","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Singapore\/title"},{"value":[{"text":"PingOneGeoSingapore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Singapore\/fragments"},{"value":"PingOneGeoEurope","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Europe\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneGeoEurope"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Europe\/fragments"},{"value":"PingOneGeoCanada","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Canada\/title"},{"value":[{"kind":"identifier","text":"PingOneGeoCanada"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Canada\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title","value":"PingOneGeo","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments","op":"replace","value":[{"text":"PingOneGeo","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PingOneGeo"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle"},{"value":"PingOneGeoAustralia","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Australia\/title"},{"value":[{"text":"PingOneGeoAustralia","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1Australia\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1NorthAmerica\/title","value":"PingOneGeoNorthAmerica","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo~1NorthAmerica\/fragments","value":[{"kind":"identifier","text":"PingOneGeoNorthAmerica"}]}]}]}