{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone"]},{"paths":["\/documentation\/pingonesdk\/pingone"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/authenticate(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(geo:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getOneTimePasscode(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getUNNotificationCategories()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/migrateFromPingID(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processIdToken(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotification(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pushNotification(allowed:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/removePingOneLocalData()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/sendLogs(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDevicePairedAfterReinstall(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(token:type:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/testRemoteNotification(_:completionHandler:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType"],"title":"Enumerations","generated":true,"anchor":"Enumerations"}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH"]}],"sections":[],"metadata":{"roleHeading":"Class","title":"PingOne","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PingOne","kind":"identifier"}],"symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PingOne"}],"modules":[{"name":"PingOneSDK"}],"externalID":"c:@M@PingOneSDK@objc(cs)PingOne"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.pingIdentity.PingOneSDK/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"abstract":[{"type":"text","text":"Type that describes the APNS environment."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","title":"PingOne.APNSDeviceTokenType","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/setDeviceToken(token:type:completionHandler:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDeviceToken","kind":"identifier"},{"text":"(","kind":"text"},{"text":"token","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"APNSDeviceTokenType","preciseIdentifier":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"]?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"text":"Set device remote notification token","type":"text"}],"type":"topic","title":"setDeviceToken(token:type:completionHandler:)","navigatorTitle":[{"text":"setDeviceTokenWithToken:type:completionHandler:","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/setdevicetoken(token:type:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(token:type:completionHandler:)","kind":"symbol","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/migrateFromPingID(completionHandler:)":{"navigatorTitle":[{"text":"migrateFromPingIDWithCompletionHandler:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"migrateFromPingID"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"status"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@E@MigrationStatus","text":"MigrationStatus","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"response","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"PairingInfo","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/migrateFromPingID(completionHandler:)","abstract":[{"text":"Migrate from PingID","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/pingone\/migratefrompingid(completionhandler:)","kind":"symbol","title":"migrateFromPingID(completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/generateMobilePayload(completionHandler:)":{"abstract":[{"text":"Generate a payload string for any communication needed between the customer mobile app and the PingOne server.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateMobilePayload"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"payload","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"generateMobilePayloadWithCompletionHandler:","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/generatemobilepayload(completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload(completionHandler:)","kind":"symbol","title":"generateMobilePayload(completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getInfo(completion:)":{"abstract":[{"text":"Get info","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getInfo","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"deviceInfo","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"errors","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"]?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/pingonesdk\/pingone\/getinfo(completion:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(completion:)","title":"getInfo(completion:)","type":"topic","navigatorTitle":[{"text":"getInfoWithCompletion:","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getUNNotificationCategories()":{"url":"\/documentation\/pingonesdk\/pingone\/getunnotificationcategories()","title":"getUNNotificationCategories()","role":"symbol","abstract":[{"text":"Get PingOne remote notification categories","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getUNNotificationCategories","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationCategory","text":"UNNotificationCategory"},{"text":">","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"getUNNotificationCategories","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getUNNotificationCategories()"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"title":"PingOne","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"},"doc://com.pingIdentity.PingOneSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/testRemoteNotification(_:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/testremotenotification(_:completionhandler:)","title":"testRemoteNotification(_:completionHandler:)","role":"symbol","abstract":[{"text":"Run push notification test","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"testRemoteNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"results","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest","text":"NotificationTest"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"status","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NotificationTest","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationTest"},{"kind":"text","text":"."},{"preciseIdentifier":"s:10PingOneSDK16NotificationTestC0E6ResultO","kind":"typeIdentifier","text":"TestResult"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"testRemoteNotification:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/testRemoteNotification(_:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"forRemoteNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"notificationObject"},{"text":": ","kind":"text"},{"text":"NotificationObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"deprecated":true,"abstract":[{"text":"Process remote notification action","type":"text"}],"type":"topic","title":"processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)","navigatorTitle":[{"kind":"identifier","text":"processRemoteNotificationAction:forRemoteNotification:completionHandler:"}],"url":"\/documentation\/pingonesdk\/pingone\/processremotenotificationaction(_:forremotenotification:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)","kind":"symbol","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/pair(_:completion:)":{"url":"\/documentation\/pingonesdk\/pingone\/pair(_:completion:)","title":"pair(_:completion:)","role":"symbol","abstract":[{"type":"text","text":"Pair device"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pair","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"text":"PairingInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingInfo"},{"kind":"text","text":"?, "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pair:completion:"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completion:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getOneTimePasscode(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getOneTimePasscode"},{"text":"((","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"passcodeInfo","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"OneTimePasscodeInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Get one time passcode","type":"text"}],"type":"topic","title":"getOneTimePasscode(_:)","navigatorTitle":[{"kind":"identifier","text":"getOneTimePasscode:"}],"url":"\/documentation\/pingonesdk\/pingone\/getonetimepasscode(_:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getOneTimePasscode(_:)","kind":"symbol","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/configure(geo:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/configure(geo:completionhandler:)","title":"configure(geo:completionHandler:)","role":"symbol","abstract":[{"type":"text","text":"Initializes the PingOne SDK for a specific geographical server."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"geo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"configureWithGeo:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(geo:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/processIdToken(_:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/processidtoken(_:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processIdToken(_:completionHandler:)","abstract":[{"text":"Pair with automatic enrollment","type":"text"}],"title":"processIdToken(_:completionHandler:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"processIdToken:completionHandler:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processIdToken"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pairingObject"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PairingObject","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)PairingObject"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)":{"title":"processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","navigatorTitle":[{"text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","kind":"identifier"}],"abstract":[{"text":"Process remote notification action","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/pingonesdk\/pingone\/processremotenotificationaction(_:authenticationmethod:forremotenotification:completionhandler:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"authenticationMethod","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"forRemoteNotification","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"notificationObject","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject","text":"NotificationObject"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/setDevicePairedAfterReinstall(_:)":{"kind":"symbol","deprecated":true,"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDevicePairedAfterReinstall"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setDevicePairedAfterReinstall:","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/setdevicepairedafterreinstall(_:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDevicePairedAfterReinstall(_:)","title":"setDevicePairedAfterReinstall(_:)","abstract":[{"text":"The developer can decide if the device will stay paired after app reinstallation. This method should only be called once.","type":"text"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/pushNotification(allowed:)":{"url":"\/documentation\/pingonesdk\/pingone\/pushnotification(allowed:)","title":"pushNotification(allowed:)","role":"symbol","abstract":[{"text":"Allow push notification","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pushNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"allowed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"allowPushNotifications:"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pushNotification(allowed:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/s7CVarArgP":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/processRemoteNotification(_:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/processremotenotification(_:completionhandler:)","title":"processRemoteNotification(_:completionHandler:)","role":"symbol","abstract":[{"text":"Process the remote notification received from PingOne.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processRemoteNotification","kind":"identifier"},{"text":"([","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"], ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"notificationObject","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NotificationObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)NotificationObject"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"processRemoteNotification:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotification(_:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/generateMobilePayload()":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload()","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingone\/generatemobilepayload()","abstract":[{"text":"Generate a payload string for any communication needed between the customer mobile app and the PingOne server.","type":"text"}],"navigatorTitle":[{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"}],"deprecated":true,"title":"generateMobilePayload()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generateMobilePayload","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/sendLogs(completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/sendlogs(completionhandler:)","title":"sendLogs(completionHandler:)","role":"symbol","abstract":[{"text":"Send logs","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendLogs","kind":"identifier"},{"kind":"text","text":"("},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"supportId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"sendLogsWithCompletionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/sendLogs(completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getInfo(_:)":{"abstract":[{"text":"Get info","type":"text"}],"url":"\/documentation\/pingonesdk\/pingone\/getinfo(_:)","type":"topic","title":"getInfo(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getInfo","kind":"identifier"},{"text":"((","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"activeUsers","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"getInfo:","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(_:)","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/authenticate(_:completionHandler:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"authenticationObject","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AuthenticationObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticationObject"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Authenticate with code","type":"text"}],"type":"topic","title":"authenticate(_:completionHandler:)","navigatorTitle":[{"text":"authenticate:completionHandler:","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/authenticate(_:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/authenticate(_:completionHandler:)","kind":"symbol","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/removePingOneLocalData()":{"url":"\/documentation\/pingonesdk\/pingone\/removepingonelocaldata()","title":"removePingOneLocalData()","role":"symbol","abstract":[{"text":"Remove PingOne local data","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePingOneLocalData"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removePingOneLocalData"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/removePingOneLocalData()"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/pair(_:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/pair(_:completionhandler:)","type":"topic","navigatorTitle":[{"text":"pair:completionHandler:","kind":"identifier"}],"deprecated":true,"title":"pair(_:completionHandler:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pair","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Pair device"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PingOne","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"PingOne","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"PingOne","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/authenticate(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(geo:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/generateMobilePayload(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getOneTimePasscode(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getUNNotificationCategories()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/migrateFromPingID(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completion:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pair(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processIdToken(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotification(_:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pushNotification(allowed:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/removePingOneLocalData()","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/sendLogs(completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDevicePairedAfterReinstall(_:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/setDeviceToken(token:type:completionHandler:)","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/testRemoteNotification(_:completionHandler:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOne"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(token:type:completionHandler:)\/title","value":"setDeviceTokenWithToken:type:completionHandler:"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDeviceToken(token:type:completionHandler:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setDeviceTokenWithToken:type:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1migrateFromPingID(completionHandler:)\/title","value":"migrateFromPingIDWithCompletionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1migrateFromPingID(completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"migrateFromPingIDWithCompletionHandler:","kind":"identifier"}],"op":"replace"},{"value":"generateMobilePayloadWithCompletionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload(completionHandler:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"generateMobilePayloadWithCompletionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload(completionHandler:)\/fragments"},{"value":"getInfoWithCompletion:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(completion:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"getInfoWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(completion:)\/fragments"},{"op":"replace","value":"getUNNotificationCategories","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getUNNotificationCategories()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getUNNotificationCategories()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getUNNotificationCategories","kind":"identifier"}]},{"value":"PingOne","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","op":"replace"},{"value":[{"kind":"identifier","text":"PingOne"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PingOne"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1testRemoteNotification(_:completionHandler:)\/title","value":"testRemoteNotification:completionHandler:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"testRemoteNotification:completionHandler:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1testRemoteNotification(_:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)\/title","op":"replace","value":"processRemoteNotificationAction:forRemoteNotification:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:forRemoteNotification:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction:forRemoteNotification:completionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completion:)\/title","value":"pair:completion:"},{"value":[{"kind":"text","text":"+ "},{"text":"pair:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completion:)\/fragments"},{"value":"getOneTimePasscode:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getOneTimePasscode(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"getOneTimePasscode:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getOneTimePasscode(_:)\/fragments"},{"value":"configureWithGeo:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(geo:completionHandler:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithGeo:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(geo:completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processIdToken(_:completionHandler:)\/title","value":"processIdToken:completionHandler:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"processIdToken:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processIdToken(_:completionHandler:)\/fragments"},{"op":"replace","value":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"processRemoteNotificationAction:authenticationMethod:forRemoteNotification:completionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotificationAction(_:authenticationMethod:forRemoteNotification:completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDevicePairedAfterReinstall(_:)\/title","value":"setDevicePairedAfterReinstall:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDevicePairedAfterReinstall:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1setDevicePairedAfterReinstall(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pushNotification(allowed:)\/title","value":"allowPushNotifications:"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pushNotification(allowed:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"allowPushNotifications:","kind":"identifier"}],"op":"replace"},{"value":"processRemoteNotification:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotification(_:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1processRemoteNotification(_:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"processRemoteNotification:completionHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload()\/title","value":"generateMobilePayloadAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1generateMobilePayload()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"generateMobilePayloadAndReturnError:","kind":"identifier"}]},{"op":"replace","value":"sendLogsWithCompletionHandler:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1sendLogs(completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1sendLogs(completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendLogsWithCompletionHandler:","kind":"identifier"}]},{"value":"getInfo:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(_:)\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"getInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1authenticate(_:completionHandler:)\/title","value":"authenticate:completionHandler:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"authenticate:completionHandler:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1authenticate(_:completionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1removePingOneLocalData()\/title","value":"removePingOneLocalData","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"removePingOneLocalData","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1removePingOneLocalData()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completionHandler:)\/title","value":"pair:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pair(_:completionHandler:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"pair:completionHandler:","kind":"identifier"}],"op":"replace"}]}]}