{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(completionHandler:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"please use approve(withAuthenticationMethod:completionHandler) instead","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"approveWithCompletionHandler:","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(im)approveWithCompletionHandler:","title":"approve(completionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"approve"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":[]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"approve","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Will return NSError in case of an error."}],"type":"paragraph"}]}]}],"abstract":[{"type":"text","text":"Approve authentication"}],"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/approve(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/approve(completionhandler:)"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/approve(completionHandler:)":{"title":"approve(completionHandler:)","role":"symbol","abstract":[{"text":"Approve authentication","type":"text"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(completionHandler:)","url":"\/documentation\/pingonesdk\/notificationobject\/approve(completionhandler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"approveWithCompletionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","url":"\/documentation\/pingonesdk\/notificationobject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"approveWithCompletionHandler:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"approveWithCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"approveWithCompletionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"inlineContent":[{"type":"text","text":"Will return NSError in case of an error."}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(completionHandler:)\/title","op":"replace","value":"approveWithCompletionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveWithCompletionHandler:"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(completionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"kind":"identifier","text":"NotificationObject"}]},{"value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle"}]}]}