{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"abstract":[{"type":"text","text":"Approve authentication"}],"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/approve(withauthenticationmethod:numbermatchingpickedvalue:completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/approve(withauthenticationmethod:numbermatchingpickedvalue:completionhandler:)"]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"approve","kind":"identifier"},{"kind":"text","text":"("},{"text":"withAuthenticationMethod","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"numberMatchingPickedValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","symbolKind":"method","title":"approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(im)approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","modules":[{"name":"PingOneSDK"}],"role":"symbol","navigatorTitle":[{"text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"approve"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withAuthenticationMethod"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"numberMatchingPickedValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"completionHandler"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"withAuthenticationMethod","content":[{"inlineContent":[{"type":"text","text":"The "},{"code":"String","type":"codeVoice"},{"text":" is the authentication method that was used to authenticate the user on the authenticating device, for example, fpt (fingerprint), face (facial recognition) etc. Refer to the “amr” (Authentication Method Reference) values in https:\/\/tools.ietf.org\/html\/rfc8176\/#section-2 .","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Will return NSError in case of an error.","type":"text"}],"type":"paragraph"}],"name":"completionHandler"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","url":"\/documentation\/pingonesdk\/notificationobject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)":{"title":"approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","role":"symbol","abstract":[{"type":"text","text":"Approve authentication"}],"type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)","url":"\/documentation\/pingonesdk\/notificationobject\/approve(withauthenticationmethod:numbermatchingpickedvalue:completionhandler:)","kind":"symbol","navigatorTitle":[{"text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"approve","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withAuthenticationMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"numberMatchingPickedValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"approveWithAuthenticationMethod:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"withAuthenticationMethod","kind":"internalParam"},{"kind":"text","text":" "},{"text":"numberMatchingPickedValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"numberMatchingPickedValue"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"String"},{"type":"text","text":" is the authentication method that was used to authenticate the user on the authenticating device, for example, fpt (fingerprint), face (facial recognition) etc. Refer to the “amr” (Authentication Method Reference) values in https:\/\/tools.ietf.org\/html\/rfc8176\/#section-2 ."}]}],"name":"withAuthenticationMethod"},{"content":[{"inlineContent":[{"type":"text","text":"Will return NSError in case of an error."}],"type":"paragraph"}],"name":"completionHandler"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","value":[{"kind":"identifier","text":"NotificationObject"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle","value":[{"text":"NotificationObject","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)\/title","op":"replace","value":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"approveWithAuthenticationMethod:numberMatchingPickedValue:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1approve(withAuthenticationMethod:numberMatchingPickedValue:completionHandler:)\/fragments"}]}]}