{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authCanceled","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authentication","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/done","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/none"]},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"kind":"symbol","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NotificationType"}],"title":"NotificationObject.NotificationType","symbolKind":"enum","role":"symbol","modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationType","kind":"identifier"}],"externalID":"s:10PingOneSDK18NotificationObjectC0D4TypeO","roleHeading":"Enumeration"},"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","url":"\/documentation\/pingonesdk\/notificationobject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/none":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/none","title":"NotificationObject.NotificationType.none","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification was not recognized."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]},"doc://com.pingIdentity.PingOneSDK/SY":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"title":"NotificationObject.NotificationType","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/authCanceled":{"abstract":[{"text":"Authentication process was canceled by the user.","type":"text"}],"kind":"symbol","title":"NotificationObject.NotificationType.authCanceled","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authCanceled","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/authcanceled","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authCanceled"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/done":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/done","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"done","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Notification process has finished. No further action is required."}],"title":"NotificationObject.NotificationType.done","kind":"symbol","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/done"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/init(rawvalue:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/Equatable-Implementations":{"kind":"article","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/equatable-implementations","role":"collectionGroup","abstract":[],"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/Equatable-Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/authentication":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/authentication","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authentication","type":"topic","kind":"symbol","title":"NotificationObject.NotificationType.authentication","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authentication"}],"abstract":[{"type":"text","text":"Authentication notification that should be presented to the user and followed with the "},{"code":"approve","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"deny"},{"text":" method.","type":"text"}]},"doc://com.pingIdentity.PingOneSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/RawRepresentable-Implementations","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","op":"replace","value":[{"text":"NotificationObject","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle","value":[{"kind":"identifier","text":"NotificationObject"}]}]}]}