{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/timeoutduration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/timeoutduration"]}],"abstract":[{"type":"text","text":"The maximum time duration allowed from getting push till user response."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/timeoutDuration","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"timeoutDuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"timeoutDuration","role":"symbol","externalID":"c:@M@PingOneSDK@objc(cs)NotificationObject(py)timeoutDuration","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"timeoutDuration"}],"modules":[{"name":"PingOneSDK"}],"symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"timeoutDuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/timeoutDuration":{"kind":"symbol","url":"\/documentation\/pingonesdk\/notificationobject\/timeoutduration","role":"symbol","abstract":[{"text":"The maximum time duration allowed from getting push till user response.","type":"text"}],"type":"topic","title":"timeoutDuration","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/timeoutDuration","navigatorTitle":[{"kind":"identifier","text":"timeoutDuration"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"timeoutDuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","url":"\/documentation\/pingonesdk\/notificationobject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"timeoutDuration","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"timeoutDuration"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"timeoutDuration"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"timeoutDuration","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1timeoutDuration\/title"},{"value":[{"kind":"identifier","text":"timeoutDuration"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject~1timeoutDuration\/fragments","op":"replace"},{"op":"replace","value":"NotificationObject","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationObject"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle","value":[{"text":"NotificationObject","kind":"identifier"}]}]}]}