{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authCanceled","kind":"identifier"}],"symbolKind":"case","externalID":"s:10PingOneSDK18NotificationObjectC0D4TypeO12authCanceledyA2EmF","modules":[{"name":"PingOneSDK"}],"roleHeading":"Case","role":"symbol","title":"NotificationObject.NotificationType.authCanceled"},"abstract":[{"text":"Authentication process was canceled by the user.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authCanceled"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/authcanceled"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authCanceled"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"type":"topic","kind":"symbol","title":"NotificationObject.NotificationType","role":"symbol","navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/authCanceled":{"title":"NotificationObject.NotificationType.authCanceled","abstract":[{"type":"text","text":"Authentication process was canceled by the user."}],"type":"topic","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/authcanceled","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/authCanceled","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authCanceled","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","kind":"symbol","type":"topic","abstract":[{"text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject"}},"variantOverrides":[{"patch":[{"value":"NotificationObject","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationObject"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments"},{"value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}