{"sections":[],"kind":"symbol","abstract":[{"text":"Notification process has finished. No further action is required.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"done"}],"symbolKind":"case","externalID":"s:10PingOneSDK18NotificationObjectC0D4TypeO4doneyA2EmF","modules":[{"name":"PingOneSDK"}],"role":"symbol","roleHeading":"Case","title":"NotificationObject.NotificationType.done"},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/done","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"done","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/done"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/done":{"title":"NotificationObject.NotificationType.done","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"done"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/done","abstract":[{"type":"text","text":"Notification process has finished. No further action is required."}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/done"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"type":"topic","kind":"symbol","title":"NotificationObject.NotificationType","role":"symbol","navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","kind":"symbol","type":"topic","abstract":[{"text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","role":"symbol","url":"\/documentation\/pingonesdk\/notificationobject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","op":"replace","value":[{"kind":"identifier","text":"NotificationObject"}]},{"value":[{"text":"NotificationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle"}]}]}