{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum"]]},"metadata":{"modules":[{"name":"PingOneSDK"}],"symbolKind":"case","title":"NotificationObject.NotificationType.none","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"externalID":"s:10PingOneSDK18NotificationObjectC0D4TypeO4noneyA2EmF"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/none","interfaceLanguage":"swift"},"abstract":[{"text":"Notification was not recognized.","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/none"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum":{"abstract":[{"type":"text","text":"Type that describes the purpose of the notification."}],"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationType"}],"navigatorTitle":[{"text":"NotificationType","kind":"identifier"}],"title":"NotificationObject.NotificationType","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject/NotificationType-swift.enum/none":{"url":"\/documentation\/pingonesdk\/notificationobject\/notificationtype-swift.enum\/none","title":"NotificationObject.NotificationType.none","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Notification was not recognized."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject\/NotificationType-swift.enum\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationObject"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationObject","url":"\/documentation\/pingonesdk\/notificationobject","navigatorTitle":[{"kind":"identifier","text":"NotificationObject"}],"title":"NotificationObject","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Notification Object represents an authentication request via remote notification. It can be approved or denied."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/title","value":"NotificationObject","op":"replace"},{"value":[{"kind":"identifier","text":"NotificationObject"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NotificationObject"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationObject\/navigatorTitle","op":"replace"}]}]}