{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/authenticationobject\/status"]},{"paths":["\/documentation\/pingonesdk\/authenticationobject\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"status","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@objc(cs)AuthenticationObject(py)status","modules":[{"name":"PingOneSDK"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/status","interfaceLanguage":"swift"},"abstract":[{"text":"String value returned from a server when a user calls an authenticate API method. Possible values: can be ","type":"text"},{"type":"codeVoice","code":"CLAIMED"},{"text":", ","type":"text"},{"type":"codeVoice","code":"EXPIRED"},{"text":", ","type":"text"},{"code":"DENIED","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"COMPLETED"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationObject","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"title":"AuthenticationObject","abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"url":"\/documentation\/pingonesdk\/authenticationobject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","kind":"symbol","type":"topic","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/status":{"url":"\/documentation\/pingonesdk\/authenticationobject\/status","navigatorTitle":[{"kind":"identifier","text":"status"}],"title":"status","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/status","type":"topic","role":"symbol","abstract":[{"type":"text","text":"String value returned from a server when a user calls an authenticate API method. Possible values: can be "},{"code":"CLAIMED","type":"codeVoice"},{"text":", ","type":"text"},{"code":"EXPIRED","type":"codeVoice"},{"type":"text","text":", "},{"code":"DENIED","type":"codeVoice"},{"type":"text","text":" or "},{"code":"COMPLETED","type":"codeVoice"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"status","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"status"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title","op":"replace","value":"AuthenticationObject"},{"op":"replace","value":[{"text":"AuthenticationObject","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/navigatorTitle","value":[{"text":"AuthenticationObject","kind":"identifier"}]},{"value":"status","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1status\/title"},{"value":[{"text":"status","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1status\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}