{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject"]]},"abstract":[{"type":"text","text":"String that determines if user approval is required to complete an authentication. Possible values: "},{"type":"codeVoice","code":"REQUIRED"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"NOT_REQUIRED"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"userApproval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/authenticationobject\/userapproval"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/authenticationobject\/userapproval"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/userApproval"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userApproval"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"userApproval","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"userApproval"}],"externalID":"c:@M@PingOneSDK@objc(cs)AuthenticationObject(py)userApproval","role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/userApproval":{"url":"\/documentation\/pingonesdk\/authenticationobject\/userapproval","navigatorTitle":[{"kind":"identifier","text":"userApproval"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/userApproval","role":"symbol","abstract":[{"text":"String that determines if user approval is required to complete an authentication. Possible values: ","type":"text"},{"type":"codeVoice","code":"REQUIRED"},{"type":"text","text":" and "},{"code":"NOT_REQUIRED","type":"codeVoice"}],"title":"userApproval","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userApproval"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationObject","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"title":"AuthenticationObject","abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"url":"\/documentation\/pingonesdk\/authenticationobject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"userApproval"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"userApproval","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"userApproval","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"userApproval","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1userApproval\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1userApproval\/fragments","value":[{"kind":"identifier","text":"userApproval"}]},{"value":"AuthenticationObject","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title"},{"op":"replace","value":[{"text":"AuthenticationObject","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticationObject"}],"op":"replace"}]}]}