{"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/users","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"users"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"users","kind":"identifier"},{"text":": [[","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]]?"}],"title":"users","modules":[{"name":"PingOneSDK"}],"roleHeading":"Instance Property","externalID":"c:@M@PingOneSDK@objc(cs)AuthenticationObject(py)users","role":"symbol"},"variants":[{"paths":["\/documentation\/pingonesdk\/authenticationobject\/users"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/authenticationobject\/users"]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"List of users that are paired to this device. Each user object can contain the following String variables: ","type":"text"},{"code":"userId","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"email"},{"text":", ","type":"text"},{"type":"codeVoice","code":"given"},{"type":"text","text":", "},{"type":"codeVoice","code":"family"},{"type":"text","text":" and "},{"type":"codeVoice","code":"username"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"users","kind":"identifier"},{"kind":"text","text":": [["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]]?","kind":"text"}]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationObject","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"title":"AuthenticationObject","abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"url":"\/documentation\/pingonesdk\/authenticationobject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","kind":"symbol","type":"topic","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject/users":{"role":"symbol","navigatorTitle":[{"text":"users","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject\/users","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"users","kind":"identifier"},{"kind":"text","text":": [["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]]?"}],"type":"topic","title":"users","abstract":[{"text":"List of users that are paired to this device. Each user object can contain the following String variables: ","type":"text"},{"type":"codeVoice","code":"userId"},{"type":"text","text":", "},{"type":"codeVoice","code":"email"},{"text":", ","type":"text"},{"code":"given","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"family"},{"type":"text","text":" and "},{"type":"codeVoice","code":"username"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/pingonesdk\/authenticationobject\/users"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"users","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"users"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSDictionary<NSString *,id> *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"users","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title","value":"AuthenticationObject","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments","value":[{"kind":"identifier","text":"AuthenticationObject"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/navigatorTitle","value":[{"kind":"identifier","text":"AuthenticationObject"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1users\/title","value":"users"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject~1users\/fragments","op":"replace","value":[{"text":"users","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}