{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Will return NSError in case of an error."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/pairingobject\/approve(completionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/pairingobject\/approve(completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Approve pairing"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"approveWithCompletionHandler:"}],"role":"symbol","title":"approve(completionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)PairingObject(im)approveWithCompletionHandler:","modules":[{"name":"PingOneSDK"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"please use approve(completion: @escaping (_ response: PairingInfo?, _ error: NSError?) -> Void)"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject":{"role":"symbol","title":"PairingObject","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PairingObject"}],"abstract":[{"type":"text","text":"PairingObject represents a pairing request that can be approved or ignored."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PairingObject"}],"url":"\/documentation\/pingonesdk\/pairingobject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PairingObject/approve(completionHandler:)":{"deprecated":true,"role":"symbol","title":"approve(completionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"approve"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Approve pairing"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PairingObject\/approve(completionHandler:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"approveWithCompletionHandler:"}],"url":"\/documentation\/pingonesdk\/pairingobject\/approve(completionhandler:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"approveWithCompletionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveWithCompletionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"approveWithCompletionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSError *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/title","value":"PairingObject"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject\/fragments","value":[{"kind":"identifier","text":"PairingObject"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completionHandler:)\/title","value":"approveWithCompletionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PairingObject~1approve(completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"approveWithCompletionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}