{"abstract":[{"text":"Test failed, push notification will not show.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum\/fail"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum\/fail","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fail","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fail","kind":"identifier"}],"role":"symbol","roleHeading":"Case","externalID":"s:10PingOneSDK16NotificationTestC0E6ResultO4failyA2EmF","title":"NotificationTest.TestResult.fail","modules":[{"name":"PingOneSDK"}],"symbolKind":"case"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum/fail":{"abstract":[{"type":"text","text":"Test failed, push notification will not show."}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum\/fail","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum\/fail","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fail"}],"title":"NotificationTest.TestResult.fail","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","type":"topic","role":"collection","url":"\/documentation\/pingonesdk","kind":"symbol","title":"PingOneSDK","abstract":[]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"title":"NotificationTest.TestResult","type":"topic","abstract":[{"text":"Public enum that describes the notification test result.","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TestResult"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum","navigatorTitle":[{"text":"TestResult","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","type":"topic","role":"symbol","url":"\/documentation\/pingonesdk\/notificationtest","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}],"title":"NotificationTest","navigatorTitle":[{"kind":"identifier","text":"NotificationTest"}],"abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","op":"replace","value":"NotificationTest"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments","value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NotificationTest"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}