{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum\/warning"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum"]]},"abstract":[{"type":"text","text":"Test failed but possibly push notification will show with some limitation."}],"metadata":{"role":"symbol","externalID":"s:10PingOneSDK16NotificationTestC0E6ResultO7warningyA2EmF","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"title":"NotificationTest.TestResult.warning","roleHeading":"Case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum\/warning"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"url":"\/documentation\/pingonesdk\/notificationtest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum/warning":{"title":"NotificationTest.TestResult.warning","type":"topic","abstract":[{"text":"Test failed but possibly push notification will show with some limitation.","type":"text"}],"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum\/warning","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum\/warning","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestResult-swift.enum":{"url":"\/documentation\/pingonesdk\/notificationtest\/testresult-swift.enum","type":"topic","navigatorTitle":[{"text":"TestResult","kind":"identifier"}],"title":"NotificationTest.TestResult","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TestResult"}],"kind":"symbol","abstract":[{"type":"text","text":"Public enum that describes the notification test result."}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestResult-swift.enum"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","value":"NotificationTest"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments","value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NotificationTest"}]}]}]}