{"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType"},"relationshipsSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/SQ","doc:\/\/com.pingIdentity.PingOneSDK\/SH","doc:\/\/com.pingIdentity.PingOneSDK\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"topicSections":[{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/production","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/sandbox"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/Equatable-Implementations","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"abstract":[{"type":"text","text":"Type that describes the APNS environment."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"APNSDeviceTokenType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"type":"text","text":"It is possible to establish a connection between the PingOne server and one of the following Apple servers:"},{"type":"text","text":" "},{"text":"Development (","type":"text"},{"type":"codeVoice","code":"sandbox"},{"text":") or ","type":"text"},{"type":"codeVoice","code":"production"},{"type":"text","text":" server."}],"type":"paragraph"}]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"roleHeading":"Enumeration","title":"PingOne.APNSDeviceTokenType","externalID":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","modules":[{"name":"PingOneSDK"}],"symbolKind":"enum"},"kind":"symbol","sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"abstract":[{"type":"text","text":"Type that describes the APNS environment."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","title":"PingOne.APNSDeviceTokenType","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/RawRepresentable-Implementations":{"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/RawRepresentable-Implementations"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"title":"PingOne","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"},"doc://com.pingIdentity.PingOneSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/production":{"type":"topic","title":"PingOne.APNSDeviceTokenType.production","url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/production","abstract":[{"type":"text","text":"Production environment."}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/production","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"production","kind":"identifier"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/SH":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/equatable-implementations","abstract":[],"kind":"article","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/Equatable-Implementations","role":"collectionGroup"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/init(rawValue:)":{"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/init(rawValue:)"},"doc://com.pingIdentity.PingOneSDK/SQ":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/sandbox":{"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/sandbox","type":"topic","title":"PingOne.APNSDeviceTokenType.sandbox","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sandbox","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Sandbox environment.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/sandbox"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"text":"PingOne","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"PingOne"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}