{"abstract":[{"type":"text","text":"Authenticate with code"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authCode"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authenticationObject"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AuthenticationObject","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticationObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"authCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"String value of the authentication code, parsed from QR or manual input."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"PingOne SDK provides an ability to authenticate via scanning the QR code."},{"text":" ","type":"text"},{"text":"The retrieved value should be passed to the PingOne SDK using the following API method.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/authenticate(_:completionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"PingOneSDK"}],"title":"authenticate(_:completionHandler:)","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)authenticate:completionHandler:","navigatorTitle":[{"text":"authenticate:completionHandler:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"authenticate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completionHandler"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"authenticationObject"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticationObject","kind":"typeIdentifier","text":"AuthenticationObject"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/authenticate(_:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/authenticate(_:completionhandler:)"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/authenticate(_:completionHandler:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"authenticationObject","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AuthenticationObject","kind":"typeIdentifier","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticationObject"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Authenticate with code","type":"text"}],"type":"topic","title":"authenticate(_:completionHandler:)","navigatorTitle":[{"text":"authenticate:completionHandler:","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/authenticate(_:completionhandler:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/authenticate(_:completionHandler:)","kind":"symbol","role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"title":"PingOne","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticationObject":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AuthenticationObject","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","type":"topic","abstract":[{"text":"Public class that contains data of authenticate with code response","type":"text"}],"title":"AuthenticationObject","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationObject"}],"url":"\/documentation\/pingonesdk\/authenticationobject"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"authenticate:completionHandler:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"authenticate:completionHandler:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"authenticate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"authCode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"text":"AuthenticationObject","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticationObject","preciseIdentifier":"c:@M@PingOneSDK@objc(cs)AuthenticationObject","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"String value of the authentication code, parsed from QR or manual input."}]}],"name":"authCode"}]},"op":"replace"},{"value":"authenticate:completionHandler:","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1authenticate(_:completionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1authenticate(_:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"authenticate:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","op":"replace","value":"PingOne"},{"op":"replace","value":[{"kind":"identifier","text":"PingOne"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle","value":[{"text":"PingOne","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/title","op":"replace","value":"AuthenticationObject"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/fragments","value":[{"text":"AuthenticationObject","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AuthenticationObject","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticationObject\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}