{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"geo"},{"text":": ","kind":"text"},{"text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo","kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"},{"kind":"text","text":", "},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"geo","content":[{"inlineContent":[{"type":"text","text":"The selected enum value."},{"text":" ","type":"text"},{"type":"text","text":"Possible values are: "},{"code":"NorthAmerica","type":"codeVoice"},{"type":"text","text":", "},{"code":"Europe","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"Canada"},{"text":", ","type":"text"},{"code":"Australia","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"Singapore"},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"style":"warning","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If this method is not called, the SDK will throw an error."}]}],"name":"Warning","type":"aside"}]}],"metadata":{"roleHeading":"Type Method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)configureWithGeo:completionHandler:","navigatorTitle":[{"kind":"identifier","text":"configureWithGeo:completionHandler:"}],"title":"configure(geo:completionHandler:)","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"text":"geo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"PingOneSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/configure(geo:completionhandler:)"]},{"paths":["\/documentation\/pingonesdk\/pingone\/configure(geo:completionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(geo:completionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes the PingOne SDK for a specific geographical server."}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/configure(geo:completionHandler:)":{"url":"\/documentation\/pingonesdk\/pingone\/configure(geo:completionhandler:)","title":"configure(geo:completionHandler:)","role":"symbol","abstract":[{"type":"text","text":"Initializes the PingOne SDK for a specific geographical server."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"geo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":": "},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"configureWithGeo:completionHandler:","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/configure(geo:completionHandler:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"title":"PingOne","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOneGeo":{"type":"topic","kind":"symbol","url":"\/documentation\/pingonesdk\/pingonegeo","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo","abstract":[{"type":"text","text":"Public enum that describes the geographical servers available for PingOne SDK."}],"title":"PingOneGeo","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingOneGeo"}],"navigatorTitle":[{"kind":"identifier","text":"PingOneGeo"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"configureWithGeo:completionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"configureWithGeo:completionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"configureWithGeo:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PingOneGeo","preciseIdentifier":"c:@M@PingOneSDK@E@PingOneGeo","kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOneGeo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"geo"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completionHandler"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"geo","content":[{"type":"paragraph","inlineContent":[{"text":"The selected enum value.","type":"text"},{"type":"text","text":" "},{"text":"Possible values are: ","type":"text"},{"code":"NorthAmerica","type":"codeVoice"},{"text":", ","type":"text"},{"code":"Europe","type":"codeVoice"},{"text":", ","type":"text"},{"code":"Canada","type":"codeVoice"},{"type":"text","text":", "},{"code":"Australia","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"Singapore"},{"type":"text","text":"."}]}]}],"kind":"parameters"}},{"op":"replace","value":"configureWithGeo:completionHandler:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(geo:completionHandler:)\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1configure(geo:completionHandler:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"configureWithGeo:completionHandler:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"text":"PingOne","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"PingOne"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/title","value":"PingOneGeo"},{"op":"replace","value":[{"kind":"identifier","text":"PingOneGeo"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOneGeo\/navigatorTitle","value":[{"kind":"identifier","text":"PingOneGeo"}]}]}]}