{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activeUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns all the users that are paired to the device."},{"type":"text","text":" "},{"type":"text","text":"For each user the response includes its user id, first name, last name and the device id."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns all the paired users from the PingOne server."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"{"},{"type":"text","text":" "},{"type":"text","text":"“users” : ["},{"type":"text","text":" "},{"type":"text","text":"{"},{"type":"text","text":" "},{"type":"text","text":"“id” : “6f05692a-b34b-4036-ae4d-ab1810ec651c”,"},{"type":"text","text":" "},{"type":"text","text":"“environment” : {"},{"type":"text","text":" "},{"type":"text","text":"“id” : “1e41d166-8012-4fa2-b755-15cd7c8a03de”"},{"type":"text","text":" "},{"type":"text","text":"},"},{"type":"text","text":" "},{"type":"text","text":"“device” : {"},{"type":"text","text":" "},{"type":"text","text":"“id” : “897fbc68-57d2-4b1e-84c8-dd36289d2b8b”"},{"type":"text","text":" "},{"type":"text","text":"},"},{"type":"text","text":" "},{"type":"text","text":"“name” : {"},{"type":"text","text":" "},{"type":"text","text":"“given” : “John”,"},{"type":"text","text":" "},{"type":"text","text":"“family” : “Doe”"},{"type":"text","text":" "},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"]"},{"type":"text","text":" "},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"`"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/getinfo(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/pingone\/getinfo(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get info"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInfo"},{"kind":"text","text":"(("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activeUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"getInfo(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)getInfo:","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getInfo:"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"role":"symbol","title":"PingOne","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOne"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PingOne"}],"url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getInfo(_:)":{"role":"symbol","title":"getInfo(_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getInfo"},{"kind":"text","text":"(("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"activeUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get info"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getInfo(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getInfo:"}],"url":"\/documentation\/pingonesdk\/pingone\/getinfo(_:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(NSDictionary<NSString *,id> *, NSError *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSDictionary#*$objc(cs)NSError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"kind":"identifier","text":"PingOne"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(_:)\/title","value":"getInfo:"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getInfo(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}