{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUNNotificationCategories"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UNNotificationCategory","preciseIdentifier":"c:objc(cs)UNNotificationCategory"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The remote notification categories."}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"PingOne provides the needed categories for notification. The developer may add categories."}]},{"style":"tip","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"setting UNNotificationCategory more than once results in previous settings being overwritten."}]}],"type":"aside","name":"Tip"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/getunnotificationcategories()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/pingone\/getunnotificationcategories()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getUNNotificationCategories()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Get PingOne remote notification categories"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUNNotificationCategories"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UNNotificationCategory","preciseIdentifier":"c:objc(cs)UNNotificationCategory"},{"kind":"text","text":">"}],"title":"getUNNotificationCategories()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)getUNNotificationCategories","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"getUNNotificationCategories"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"role":"symbol","title":"PingOne","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOne"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PingOne"}],"url":"\/documentation\/pingonesdk\/pingone"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/getUNNotificationCategories()":{"role":"symbol","title":"getUNNotificationCategories()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUNNotificationCategories"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UNNotificationCategory","preciseIdentifier":"c:objc(cs)UNNotificationCategory"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Get PingOne remote notification categories"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/getUNNotificationCategories()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getUNNotificationCategories"}],"url":"\/documentation\/pingonesdk\/pingone\/getunnotificationcategories()"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getUNNotificationCategories"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getUNNotificationCategories"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSSet<UNNotificationCategory *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getUNNotificationCategories"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"kind":"identifier","text":"PingOne"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getUNNotificationCategories()\/title","value":"getUNNotificationCategories"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1getUNNotificationCategories()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getUNNotificationCategories"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}