{"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pushNotification(allowed:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)allowPushNotifications:","modules":[{"name":"PingOneSDK"}],"title":"pushNotification(allowed:)","navigatorTitle":[{"text":"allowPushNotifications:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pushNotification"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"allowed"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(allowPushNotifications:) ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pushNotification"},{"kind":"text","text":"("},{"text":"allowed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"allowed","content":[{"type":"paragraph","inlineContent":[{"text":"A boolean that will tell the server to send push messages or not. Defaults to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Method that will notify the server to send or not to send push messages to this device."},{"type":"text","text":" "},{"text":"Set to false to disable SDK push notifications.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/pushnotification(allowed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/pingone\/pushnotification(allowed:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"abstract":[{"type":"text","text":"Allow push notification"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOne"}],"role":"symbol","url":"\/documentation\/pingonesdk\/pingone","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","title":"PingOne","navigatorTitle":[{"kind":"identifier","text":"PingOne"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/pushNotification(allowed:)":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pushNotification","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"allowed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"allowPushNotifications:"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/pushNotification(allowed:)","abstract":[{"type":"text","text":"Allow push notification"}],"title":"pushNotification(allowed:)","role":"symbol","kind":"symbol","url":"\/documentation\/pingonesdk\/pingone\/pushnotification(allowed:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"allowPushNotifications:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowPushNotifications:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"allowPushNotifications:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"allowed","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"allowed","content":[{"inlineContent":[{"type":"text","text":"A boolean that will tell the server to send push messages or not. Defaults to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","value":"PingOne","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"text":"PingOne","kind":"identifier"}]},{"value":[{"text":"PingOne","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle"},{"value":"allowPushNotifications:","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pushNotification(allowed:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1pushNotification(allowed:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"allowPushNotifications:","kind":"identifier"}],"op":"replace"}]}]}