{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/removepingonelocaldata()"]},{"paths":["\/documentation\/pingonesdk\/pingone\/removepingonelocaldata()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@PingOneSDK@objc(cs)PingOne(cm)removePingOneLocalData","role":"symbol","title":"removePingOneLocalData()","navigatorTitle":[{"text":"removePingOneLocalData","kind":"identifier"}],"modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removePingOneLocalData","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"]]},"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/removePingOneLocalData()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removePingOneLocalData"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"One-sided remove data method for development use only."}],"type":"paragraph"},{"name":"Warning","style":"warning","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Using this method will remove the trusted connection between the iOS SDK and the PingOne server"},{"text":" ","type":"text"},{"type":"text","text":"server in a one sided manner, where only the iOS side will be removed."},{"type":"text","text":" "},{"type":"text","text":"This method should not be used when logging out of your account."},{"type":"text","text":" "},{"type":"text","text":"This method should only be used in development."}]}]}],"kind":"content"}],"kind":"symbol","abstract":[{"text":"Remove PingOne local data","type":"text"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOne"}],"role":"symbol","url":"\/documentation\/pingonesdk\/pingone","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","title":"PingOne","navigatorTitle":[{"kind":"identifier","text":"PingOne"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/removePingOneLocalData()":{"title":"removePingOneLocalData()","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"removePingOneLocalData"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removePingOneLocalData","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"text":"Remove PingOne local data","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/removePingOneLocalData()","url":"\/documentation\/pingonesdk\/pingone\/removepingonelocaldata()"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"removePingOneLocalData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removePingOneLocalData"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"removePingOneLocalData","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne"},{"value":[{"text":"PingOne","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle","value":[{"text":"PingOne","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1removePingOneLocalData()\/title","value":"removePingOneLocalData","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne~1removePingOneLocalData()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"removePingOneLocalData","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}