{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/errormessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/errormessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorMessage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error code in case of authorization method failure"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel(py)errorMessage","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"errorMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"role":"symbol","title":"AuthenticatorModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticatorModel"}],"abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}],"url":"\/documentation\/pingonesdk\/authenticatormodel"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/errorMessage":{"role":"symbol","title":"errorMessage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error code in case of authorization method failure"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/errorMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorMessage"}],"url":"\/documentation\/pingonesdk\/authenticatormodel\/errormessage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"errorMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"errorMessage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"errorMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","value":[{"kind":"identifier","text":"AuthenticatorModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorMessage\/title","value":"errorMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1errorMessage\/fragments","value":[{"kind":"identifier","text":"errorMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}