{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType","preciseIdentifier":"s:10PingOneSDK18AuthenticatorModelC0D4TypeO","text":"AuthenticatorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/authenticatormodel\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/type","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The Authenticator type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticatorType","preciseIdentifier":"s:10PingOneSDK18AuthenticatorModelC0D4TypeO"}],"title":"type","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@PingOneSDK@objc(cs)AuthenticatorModel(py)type","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AuthenticatorType","preciseIdentifier":"s:10PingOneSDK18AuthenticatorModelC0D4TypeO"}],"abstract":[{"type":"text","text":"The Authenticator type"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"url":"\/documentation\/pingonesdk\/authenticatormodel\/type"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorType":{"role":"symbol","title":"AuthenticatorType","fragments":[{"kind":"identifier","text":"AuthenticatorType"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorType","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk\/authenticatortype"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorType":{"role":"symbol","title":"AuthenticatorModel.AuthenticatorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticatorType"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorType"}],"url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatortype"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"role":"symbol","title":"AuthenticatorModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticatorModel"}],"abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}],"url":"\/documentation\/pingonesdk\/authenticatormodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorType","preciseIdentifier":"c:@M@PingOneSDK@E@AuthenticatorType","text":"AuthenticatorType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1type\/title","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","value":[{"kind":"identifier","text":"AuthenticatorModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}