{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/done"},"abstract":[{"text":"Migration completed.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"done"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@MigrationStatus@MigrationStatusDone","title":"MigrationStatus.done","symbolKind":"case","role":"symbol","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"text":"MigrationStatusDone","kind":"identifier"}]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/pingonesdk\/migrationstatus\/done"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/migrationstatus\/done"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"done","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus/done":{"type":"topic","abstract":[{"type":"text","text":"Migration completed."}],"url":"\/documentation\/pingonesdk\/migrationstatus\/done","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"done"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus\/done","title":"MigrationStatus.done","navigatorTitle":[{"text":"MigrationStatusDone","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/MigrationStatus":{"abstract":[{"type":"text","text":"Enum that represents the migration status returned from the SDK"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MigrationStatus","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MigrationStatus"}],"url":"\/documentation\/pingonesdk\/migrationstatus","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/MigrationStatus","kind":"symbol","title":"MigrationStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"MigrationStatusDone","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"MigrationStatusDone"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MigrationStatusDone"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1done\/title","op":"replace","value":"MigrationStatusDone"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus~1done\/fragments","op":"replace","value":[{"text":"MigrationStatusDone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/title","op":"replace","value":"MigrationStatus"},{"value":[{"text":"MigrationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/fragments","op":"replace"},{"value":[{"text":"MigrationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1MigrationStatus\/navigatorTitle"}]}]}