{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/bundleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/bundleid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/bundleId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"There was a problem with the bundle id."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"}],"title":"ErrorCode.bundleId","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeBundleId","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeBundleId"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"role":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/bundleId":{"role":"symbol","title":"ErrorCode.bundleId","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"}],"abstract":[{"type":"text","text":"There was a problem with the bundle id."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/bundleId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeBundleId"}],"url":"\/documentation\/pingonesdk\/errorcode\/bundleid"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeBundleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeBundleId"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeBundleId"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1bundleId\/title","value":"ErrorCodeBundleId"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1bundleId\/fragments","value":[{"kind":"identifier","text":"ErrorCodeBundleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}