{"metadata":{"externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeCantUpdateGeo","symbolKind":"case","title":"ErrorCode.cantUpdateGeo","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cantUpdateGeo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeCantUpdateGeo"}],"modules":[{"name":"PingOneSDK"}],"role":"symbol","roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cantUpdateGeo","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"abstract":[{"text":"The device is already trusted with a certain geo and cannot set a new one using configure(PingOneGeo). If needed to change the geo, the device should be reset by calling the removePingOneLocalData() method.","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/cantupdategeo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/cantupdategeo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateGeo","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"PingOne SDK error codes."}],"role":"symbol","title":"ErrorCode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/cantUpdateGeo":{"type":"topic","title":"ErrorCode.cantUpdateGeo","url":"\/documentation\/pingonesdk\/errorcode\/cantupdategeo","abstract":[{"type":"text","text":"The device is already trusted with a certain geo and cannot set a new one using configure(PingOneGeo). If needed to change the geo, the device should be reset by calling the removePingOneLocalData() method."}],"navigatorTitle":[{"text":"ErrorCodeCantUpdateGeo","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/cantUpdateGeo","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cantUpdateGeo","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"ErrorCodeCantUpdateGeo","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ErrorCodeCantUpdateGeo","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"ErrorCodeCantUpdateGeo"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"ErrorCode","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateGeo\/title","value":"ErrorCodeCantUpdateGeo"},{"op":"replace","value":[{"text":"ErrorCodeCantUpdateGeo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1cantUpdateGeo\/fragments"}]}]}