{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/configureerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/configureerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/configureError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The SDK was not configured. Make sure to run the configure(PingOneGeo) method first."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureError"}],"title":"ErrorCode.configureError","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeConfigureError","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodeConfigureError"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/configureError":{"role":"symbol","title":"ErrorCode.configureError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"configureError"}],"abstract":[{"type":"text","text":"The SDK was not configured. Make sure to run the configure(PingOneGeo) method first."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/configureError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeConfigureError"}],"url":"\/documentation\/pingonesdk\/errorcode\/configureerror"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"role":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"PingOne SDK error codes."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/pingonesdk\/errorcode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeConfigureError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodeConfigureError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodeConfigureError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1configureError\/title","value":"ErrorCodeConfigureError"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1configureError\/fragments","value":[{"kind":"identifier","text":"ErrorCodeConfigureError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}