{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"deviceTokenIsMissing","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceTokenIsMissing"},"abstract":[{"text":"Device token was missing and is required to complete this action.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/devicetokenismissing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/errorcode\/devicetokenismissing"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeDeviceTokenIsMissing","roleHeading":"Case","title":"ErrorCode.deviceTokenIsMissing","modules":[{"name":"PingOneSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"deviceTokenIsMissing","kind":"identifier"}],"navigatorTitle":[{"text":"ErrorCodeDeviceTokenIsMissing","kind":"identifier"}]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"PingOne SDK error codes."}],"role":"symbol","title":"ErrorCode"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/deviceTokenIsMissing":{"url":"\/documentation\/pingonesdk\/errorcode\/devicetokenismissing","type":"topic","navigatorTitle":[{"text":"ErrorCodeDeviceTokenIsMissing","kind":"identifier"}],"title":"ErrorCode.deviceTokenIsMissing","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"deviceTokenIsMissing","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Device token was missing and is required to complete this action."}],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/deviceTokenIsMissing"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ErrorCodeDeviceTokenIsMissing","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ErrorCodeDeviceTokenIsMissing"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"ErrorCodeDeviceTokenIsMissing","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/navigatorTitle","value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace"},{"value":"ErrorCodeDeviceTokenIsMissing","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceTokenIsMissing\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1deviceTokenIsMissing\/fragments","value":[{"kind":"identifier","text":"ErrorCodeDeviceTokenIsMissing"}],"op":"replace"}]}]}