{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/errorcode\/migrationnotneeded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/pingonesdk\/errorcode\/migrationnotneeded"]}],"kind":"symbol","abstract":[{"text":"The device does not need to be migrated because it is already paired.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationNotNeeded"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"migrationNotNeeded","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"metadata":{"externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeMigrationNotNeeded","modules":[{"name":"PingOneSDK"}],"title":"ErrorCode.migrationNotNeeded","navigatorTitle":[{"text":"ErrorCodeMigrationNotNeeded","kind":"identifier"}],"role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"migrationNotNeeded"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/migrationNotNeeded":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"migrationNotNeeded"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/migrationNotNeeded","url":"\/documentation\/pingonesdk\/errorcode\/migrationnotneeded","navigatorTitle":[{"text":"ErrorCodeMigrationNotNeeded","kind":"identifier"}],"title":"ErrorCode.migrationNotNeeded","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The device does not need to be migrated because it is already paired."}],"kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"type":"topic","role":"symbol","kind":"symbol","title":"ErrorCode","abstract":[{"type":"text","text":"PingOne SDK error codes."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/pingonesdk\/errorcode","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ErrorCodeMigrationNotNeeded","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"ErrorCodeMigrationNotNeeded","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ErrorCodeMigrationNotNeeded","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ErrorCodeMigrationNotNeeded","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationNotNeeded\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1migrationNotNeeded\/fragments","value":[{"text":"ErrorCodeMigrationNotNeeded","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","op":"replace","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/navigatorTitle","op":"replace","value":[{"text":"ErrorCode","kind":"identifier"}]}]}]}