{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pairingKeyDataCenterMismatch"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/pairingkeydatacentermismatch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/pairingkeydatacentermismatch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingKeyDataCenterMismatch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Device may be paired in one regional data center only, and is already paired in another regional data center."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pairingKeyDataCenterMismatch"}],"title":"ErrorCode.pairingKeyDataCenterMismatch","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodePairingKeyDataCenterMismatch","modules":[{"name":"PingOneSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ErrorCodePairingKeyDataCenterMismatch"}]},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/pairingKeyDataCenterMismatch":{"role":"symbol","title":"ErrorCode.pairingKeyDataCenterMismatch","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pairingKeyDataCenterMismatch"}],"abstract":[{"type":"text","text":"Device may be paired in one regional data center only, and is already paired in another regional data center."}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/pairingKeyDataCenterMismatch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodePairingKeyDataCenterMismatch"}],"url":"\/documentation\/pingonesdk\/errorcode\/pairingkeydatacentermismatch"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"role":"collection","title":"PingOneSDK","abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"role":"symbol","title":"ErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ErrorCode"}],"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"url":"\/documentation\/pingonesdk\/errorcode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodePairingKeyDataCenterMismatch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ErrorCodePairingKeyDataCenterMismatch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ErrorCodePairingKeyDataCenterMismatch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingKeyDataCenterMismatch\/title","value":"ErrorCodePairingKeyDataCenterMismatch"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1pairingKeyDataCenterMismatch\/fragments","value":[{"kind":"identifier","text":"ErrorCodePairingKeyDataCenterMismatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"kind":"identifier","text":"ErrorCode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}