{"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode"]]},"abstract":[{"type":"text","text":"The client failed to establish trust with the server."}],"metadata":{"modules":[{"name":"PingOneSDK"}],"roleHeading":"Case","externalID":"c:@M@PingOneSDK@E@ErrorCode@ErrorCodeTrustFailed","navigatorTitle":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"trustFailed","kind":"identifier"}],"role":"symbol","title":"ErrorCode.trustFailed","symbolKind":"case"},"kind":"symbol","identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/trustFailed","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"trustFailed"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/pingonesdk\/errorcode\/trustfailed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/pingonesdk\/errorcode\/trustfailed"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode/trustFailed":{"abstract":[{"text":"The client failed to establish trust with the server.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trustFailed","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/errorcode\/trustfailed","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode\/trustFailed","title":"ErrorCode.trustFailed","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ErrorCodeTrustFailed"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/ErrorCode":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/ErrorCode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ErrorCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/errorcode","navigatorTitle":[{"kind":"identifier","text":"ErrorCode"}],"abstract":[{"type":"text","text":"PingOne SDK error codes."}],"role":"symbol","title":"ErrorCode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ErrorCodeTrustFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ErrorCodeTrustFailed","op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1trustFailed\/title"},{"op":"replace","value":[{"text":"ErrorCodeTrustFailed","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode~1trustFailed\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/title","value":"ErrorCode"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/fragments","value":[{"text":"ErrorCode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ErrorCode"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1ErrorCode\/navigatorTitle"}]}]}