{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/authenticatormodel\/authenticatorstatus\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10PingOneSDK18AuthenticatorModelC0D6StatusO8rawValueAESgSi_tcfc","roleHeading":"Initializer","modules":[{"name":"PingOneSDK"}],"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel":{"title":"AuthenticatorModel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorModel"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AuthenticatorModel","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/authenticatormodel","abstract":[{"type":"text","text":"AuthenticatorModel public class contains the acceptable authorization methods and its status"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorStatus":{"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticatorStatus"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatorstatus","navigatorTitle":[{"kind":"identifier","text":"AuthenticatorStatus"}],"abstract":[],"role":"symbol","title":"AuthenticatorModel.AuthenticatorStatus"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/AuthenticatorModel/AuthenticatorStatus/init(rawValue:)":{"url":"\/documentation\/pingonesdk\/authenticatormodel\/authenticatorstatus\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/AuthenticatorModel\/AuthenticatorStatus\/init(rawValue:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/title","value":"AuthenticatorModel"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"AuthenticatorModel"}]},{"value":[{"text":"AuthenticatorModel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1AuthenticatorModel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}