{"metadata":{"roleHeading":"Operator","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:10PingOneSDK16NotificationTestC0E4TypeO","symbolKind":"op","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"PingOneSDK"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/Equatable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/pingonesdk\/notificationtest\/testtype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/!=(_:_:)"},"sections":[],"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"url":"\/documentation\/pingonesdk\/notificationtest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType/!=(_:_:)":{"url":"\/documentation\/pingonesdk\/notificationtest\/testtype\/!=(_:_:)","type":"topic","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/!=(_:_:)"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","abstract":[],"url":"\/documentation\/pingonesdk\/notificationtest\/testtype\/equatable-implementations","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/Equatable-Implementations","role":"collectionGroup","kind":"article"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType","type":"topic","title":"NotificationTest.TestType","navigatorTitle":[{"text":"TestType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TestType"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/notificationtest\/testtype","abstract":[{"type":"text","text":"Public enum that describes the notification of all tests name, description, and resulstsInfo."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","value":"NotificationTest"},{"value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle","value":[{"text":"NotificationTest","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}