{"variants":[{"paths":["\/documentation\/pingonesdk\/notificationtest\/testtype\/token"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/token"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"token","kind":"identifier"}],"role":"symbol","externalID":"s:10PingOneSDK16NotificationTestC0E4TypeO5tokenyA2EmF","symbolKind":"case","modules":[{"name":"PingOneSDK"}],"title":"NotificationTest.TestType.token"},"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"token"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NotificationTest","kind":"identifier"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest","title":"NotificationTest","abstract":[{"type":"text","text":"Public class that contains data of notifications tests"}],"url":"\/documentation\/pingonesdk\/notificationtest","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotificationTest","kind":"identifier"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType":{"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType","type":"topic","title":"NotificationTest.TestType","navigatorTitle":[{"text":"TestType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TestType"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/notificationtest\/testtype","abstract":[{"type":"text","text":"Public enum that describes the notification of all tests name, description, and resulstsInfo."}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/NotificationTest/TestType/token":{"url":"\/documentation\/pingonesdk\/notificationtest\/testtype\/token","type":"topic","role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/NotificationTest\/TestType\/token","title":"NotificationTest.TestType.token","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"token","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/title","value":"NotificationTest","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/fragments","op":"replace","value":[{"kind":"identifier","text":"NotificationTest"}]},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1NotificationTest\/navigatorTitle","value":[{"text":"NotificationTest","kind":"identifier"}],"op":"replace"}]}]}