{"metadata":{"symbolKind":"property","title":"validUntil","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"PingOneSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"validUntil","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"validUntil","kind":"identifier"}],"externalID":"c:@M@PingOneSDK@objc(cs)OneTimePasscodeInfo(py)validUntil"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo\/validuntil"]},{"paths":["\/documentation\/pingonesdk\/onetimepasscodeinfo\/validuntil"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"The time of expiration of the code."},{"type":"text","text":" "},{"type":"text","text":"it is provided in double format which holds the future time in milliseconds divided by 1000 to represent seconds"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"validUntil","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validUntil","interfaceLanguage":"swift"},"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo/validUntil":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validUntil"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo\/validUntil","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo\/validuntil","title":"validUntil","kind":"symbol","role":"symbol","abstract":[{"text":"The time of expiration of the code.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"it is provided in double format which holds the future time in milliseconds divided by 1000 to represent seconds"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"validUntil"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/OneTimePasscodeInfo":{"kind":"symbol","title":"OneTimePasscodeInfo","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OneTimePasscodeInfo","kind":"identifier"}],"navigatorTitle":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"type":"topic","url":"\/documentation\/pingonesdk\/onetimepasscodeinfo","abstract":[{"text":"Public class that contains data of the One Time Passcode","type":"text"}],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/OneTimePasscodeInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"validUntil","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"validUntil","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"validUntil"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"validUntil","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validUntil\/title"},{"op":"replace","value":[{"text":"validUntil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo~1validUntil\/fragments"},{"value":"OneTimePasscodeInfo","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/title","op":"replace"},{"op":"replace","value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/fragments"},{"op":"replace","value":[{"text":"OneTimePasscodeInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1OneTimePasscodeInfo\/navigatorTitle"}]}]}