{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/hashValue"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/RawRepresentable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO","extendedModule":"Swift","role":"symbol","title":"hashValue","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"modules":[{"name":"PingOneSDK","relatedModules":["Swift"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"abstract":[],"identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","role":"collection","kind":"symbol","title":"PingOneSDK","type":"topic","url":"\/documentation\/pingonesdk"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/hashValue":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hashValue","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"type":"topic","url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/hashvalue","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/hashValue"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PingOne"}],"role":"symbol","url":"\/documentation\/pingonesdk\/pingone","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","title":"PingOne","navigatorTitle":[{"kind":"identifier","text":"PingOne"}]},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/rawrepresentable-implementations","kind":"article","role":"collectionGroup"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"abstract":[{"text":"Type that describes the APNS environment.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"APNSDeviceTokenType"}],"title":"PingOne.APNSDeviceTokenType","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"APNSDeviceTokenType"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","op":"replace","value":"PingOne"},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","value":[{"kind":"identifier","text":"PingOne"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle","value":[{"text":"PingOne","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}