{"abstract":[{"text":"Production environment.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne","doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/production"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","modules":[{"name":"PingOneSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"production","kind":"identifier"}],"externalID":"s:10PingOneSDK0aB0C19APNSDeviceTokenTypeO10productionyA2EmF","title":"PingOne.APNSDeviceTokenType.production","role":"symbol","symbolKind":"case"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"production"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/production"]}],"references":{"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType":{"abstract":[{"type":"text","text":"Type that describes the APNS environment."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"APNSDeviceTokenType","kind":"identifier"}],"navigatorTitle":[{"text":"APNSDeviceTokenType","kind":"identifier"}],"url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType","title":"PingOne.APNSDeviceTokenType","kind":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne":{"title":"PingOne","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PingOne","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/pingonesdk\/pingone","navigatorTitle":[{"text":"PingOne","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK/PingOne/APNSDeviceTokenType/production":{"type":"topic","title":"PingOne.APNSDeviceTokenType.production","url":"\/documentation\/pingonesdk\/pingone\/apnsdevicetokentype\/production","abstract":[{"type":"text","text":"Production environment."}],"kind":"symbol","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK\/PingOne\/APNSDeviceTokenType\/production","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"production","kind":"identifier"}],"role":"symbol"},"doc://com.pingIdentity.PingOneSDK/documentation/PingOneSDK":{"title":"PingOneSDK","type":"topic","identifier":"doc:\/\/com.pingIdentity.PingOneSDK\/documentation\/PingOneSDK","kind":"symbol","url":"\/documentation\/pingonesdk","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/title","value":"PingOne","op":"replace"},{"path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/fragments","op":"replace","value":[{"text":"PingOne","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.pingIdentity.PingOneSDK~1documentation~1PingOneSDK~1PingOne\/navigatorTitle","value":[{"text":"PingOne","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}